MOCK_HEATER_ON = "incubator.mock.hw.heater.on"
MOCK_TEMP_T1 = "incubator.mock.hw.temperature.t1"
MOCK_TEMP_T2 = "incubator.mock.hw.temperature.t2"
MOCK_TEMP_T3 = "incubator.mock.hw.temperature.t3"
MOCK_G_BOX = "incubator.mock.hw.box.G"