@startuml Calibration
boundary Client as client
entity Simulator as sim
database InfluxDB as db
client -> sim: run_simulation(params, input_trajectories, record)
opt record
  sim ->> db: record_results(params, simulator, results)
end
sim ->> client: results
@enduml