ROUTING_KEY_RECORDER = "incubator.record.#"
ROUTING_KEY_KF_PLANT_STATE = "incubator.record.kalmanfilter.plant.state"
ROUTING_KEY_PTSIMULATOR4 = "incubator.pt_simulator.physicaltwin.4params"
ROUTING_KEY_PLANTSIMULATOR4 = "incubator.pt_simulator.plant.4params"
ROUTING_KEY_PLANTCALIBRATOR4 = "incubator.calibrator.plant.4params"
ROUTING_KEY_LIDOPEN = "incubator.diagnosis.plant.lidopen"
