@startuml AnomalyDetector
boundary Client as client
control AnomalyDetector as det
boundary RabbitMQ as mq
client ->> det: start(estimator_routing_key)
det ->> mq: subscribe(route_key=estimator_routing_key)
loop forever
  mq ->> det: callback(msg)
  det -> det: compare_samples(msg)
  opt anomaly_detected
    det ->> mq: send_message(route_key=ROUTING_KEY_ANOMALY, anomaly)
  end
end
@enduml
