@startuml Calibration
boundary Client as client
control Calibrator as cal
entity Simulator as sim
database InfluxDB as db
client ->> cal: calibrate(start_date, end_date, simulator, n)
loop n times
  cal -> db: get_trajectories(start_date, end_date)
  return data
  cal -> sim: run(data, model, params_i)
  sim --> cal: results
  cal -> cal: residual := calc(results)
  cal -> cal: params_{i+1} := update(params_i, residual)
end
cal ->> client: params
@enduml