@startuml KalmanFilter
boundary Client as client
control KalmanFilter as kf
boundary RabbitMQ as mq
entity Simulator as mod
database InfluxDB as db
client ->> kf: start(simulator)
kf ->> mq: subscribe(route_key=ROUTING_KEY_STATE)
kf -> db: get_most_recent_params(simulator)
return params
kf -> mod: get_state_space_form(simulator, params)
return model
loop forever
  mq ->> kf: callback(sample_j)
  kf -> kf: data_{j+1} := kalman_step(model, sample_j)
  kf ->> db: record(model, data_{j+1})
end
@enduml