@startuml KalmanFilter
boundary RabbitMQServer as comm
boundary ExternalTrigger as trig
control KalmanFilter as kf
database DataAccess as db
database ModelManager as mod
trig ->> kf: start(model)
kf --> comm: subscribe()
kf -> mod: getParams(model)
return params
kf -> mod: instantiateModel(model, params)
return model_i
loop every sample_j
  comm ->> kf: sample
  kf -> kf: data_{j+1} := kalmanStep(model_i, sample_j)
  kf ->> db: recordSample(model_i, data_{j+1})
end
@enduml