@startuml LowLevelDriver
entity Plant as plt
control LowLevelDriver as lld
entity RabbitMQ as mq
loop forever
  lld -> mq: get_message(route_key=ROUTING_KEY_HEATER)
  return heatc
  lld -> mq: get_message(route_key=ROUTING_KEY_FAN)
  return fanc
  lld -> plt: set_actuator(heater=heatc)
  lld -> plt: set_actuator(fan=fanc)
  lld -> plt: read_temperatures()
  return temperatures
  lld -> lld: contruct_state_message(temperatures, heatc, fanc)
  lld -> mq: send_message(route_key=ROUTING_KEY_STATE, msg)
end
@enduml